### ISSUE TITLE
Type error in Meander object using last release of KLayout in windows

### ISSUE THREAD

**Issue by jevillegasd** [iqm-finland/KQCircuits#101]
### What happened? What you expected to happen?

Hey! When instantiating a meander PCell, an error **'TypeError: 'DPoint' is not callable** is thrown. The error source points to the PCell declaration helper function, so I couldn't trace which line in the meander definition is generating the error.  Other PCells don't seem to throw this error. I tried this using main and the latest salt package direc;ty installed from KLayout and I get the same error.

![image](https://github.com/user-attachments/assets/a575b644-b839-4940-b84b-06444f12fb35)

Best,
Juan

### Versions

KQCircuits: 4.8.2 (and main at commit #[90c2c70](https://github.com/iqm-finland/KQCircuits/commit/90c2c704f7fa06cc203c1f678aff2c139a9b70e1))
KLayout: 0.29.6 
OS: Windows 11

### Issue Severity

Medium: significant difficulty but I can work around it

**Comment by qpavsmi** [comment]
Hi! This is an issue I am working on right this moment. Starting from KLayout 0.29.5 the `PCellDeclarationHelper` class from which all `Element` subclasses are derived got a `start` function introduced. This caused `Meander` element to fail (maybe others too) because it has a parameter named `start`, that is currently clashing with KLayout's code. Expect a fix for this early next week or maybe even today.

**Comment by qpavsmi** [comment]
But yes, in the mean time, the workarounds are:
- Downgrade KLayout to 0.29.4 or older
- Rename `start` parameter in Meander, also make sure that any chips you want to use also reference the renamed parameter

**Comment by qpavsmi** [comment]
This has now been fixed as of KQCircuits v4.8.4, its compatible with KLayout >= 0.29.5. Closing issue. Feel free to reopen the issue if something is still wrong.
